spring:
  application:
    name: sb-discovery-service
    instance-id: global
  output.ansi.enabled: ALWAYS
  
  # devtools:
  #   livereload:
  #     enabled: true
      
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    peerNodeReadTimeoutMs: 10000
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.application.instance-id}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10


#
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
#     jmx:
#       exposure:
#         include: "*"
#     access:
#       default: READ_ONLY
#   endpoint:
#     info:
#       access: READ_ONLY