#
# docker compose -f bd-docker-sandbox/docker-compose.yml up -d
# docker compose -f bd-docker-sandbox/docker-compose.yml down
#
# docker compose -f bd-docker-sandbox/docker-compose.yml up -d sb-discovery-service
# docker compose -f bd-docker-sandbox/docker-compose.yml down sb-discovery-service
#
# docker compose -f bd-docker-sandbox/docker-compose.yml up -d sb-gateway-module
# docker compose -f bd-docker-sandbox/docker-compose.yml down sb-gateway-module
#
# docker compose -f bd-docker-sandbox/docker-compose.yml up -d sb-resource-server
# docker compose -f bd-docker-sandbox/docker-compose.yml down sb-resource-server
#
# docker compose -f bd-docker-sandbox/docker-compose.yml up -d sb-server-module
# docker compose -f bd-docker-sandbox/docker-compose.yml down sb-server-module
#
#
---
version: "3.9"
services:
  #
  # sb-discovery-service
  #
  sb-discovery-service:
    image: brijeshdhaker/sb-discovery-service:1.0.0
    container_name: sb-discovery-service
    hostname: sb-discovery-service.sandbox.net
    privileged: true
    healthcheck:
      test: echo $(hostname -f) || exit 1
      retries: 20
      interval: 10s
    ports:
      - "8761:8761"
    volumes:
      - ./sb-discovery-service/src/main/resources/application.yaml:/apps/configs/application.yaml
    env_file:
      - .env_docker
    environment:
      APP_LOG_DIR: /apps/var/logs/sb-applications
      APP_LOG_FILE: sb-discovery-service
    extra_hosts:
      - "hostmaster.sandbox.net:172.18.0.1"

  #
  # sb-gateway-module
  #
  sb-gateway-module:
    image: brijeshdhaker/sb-gateway-module:1.0.0
    container_name: sb-gateway-module
    hostname: sb-gateway-module.sandbox.net
    depends_on:
      sb-discovery-service:
        condition: service_healthy    
    healthcheck:
      test: echo $(hostname -f) || exit 1
      retries: 20
      interval: 10s
    restart: always
    ports:
      - "8100:8100"
    volumes:
      - ./sb-gateway-module/src/main/resources/application.yaml:/apps/configs/application.yaml
    env_file:
      - .env_docker
    environment:
      APP_LOG_DIR: /apps/var/logs/sb-applications
      APP_LOG_FILE: sb-gateway-module
    extra_hosts:
      - "hostmaster.sandbox.net:172.18.0.1"

  #
  # sb-resource-server
  #
  sb-resource-server:
    image: brijeshdhaker/sb-resource-server:1.0.0
    container_name: sb-resource-server
    hostname: sb-resource-server.sandbox.net
    healthcheck:
      test: echo $(hostname -f) || exit 1
      retries: 20
      interval: 10s
    restart: always
    depends_on:
      sb-discovery-service:
        condition: service_healthy  
    ports:
      - "8085:8085"
    volumes:
      - ./sb-resource-server/src/main/resources/application.yaml:/apps/configs/application.yaml
    env_file:
      - .env_docker
    environment:
      APP_LOG_DIR: /apps/var/logs/sb-applications
      APP_LOG_FILE: sb-resource-server
    extra_hosts:
      - "hostmaster.sandbox.net:172.18.0.1"

#
# Docker Volumes
#
volumes:
  #
  sandbox_apps_path:
    external: true

#
# Docker Networks
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net